--DDL 建立一個IoTDB資料庫
CREATE DATABASE [IoTDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IoTDB', 
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\IoTDB.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IoTDB_log', 
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\IoTDB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
